import { Toaster } from "@/components/ui/toaster";
import { lazy, Suspense } from "react";
import { Toaster as Sonner } from "@/components/ui/sonner";
import { TooltipProvider } from "@/components/ui/tooltip";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { BrowserRouter, MemoryRouter, Routes, Route, Navigate } from "react-router-dom";
import { HelmetProvider } from "react-helmet-async";
import { OrcamentoProvider } from "./context/OrcamentoProvider";
import ConsentManager from "./components/ConsentManager";
import Index from "./pages/Index"; import Blog from "./pages/Blog"; import BlogPost from "./pages/BlogPost"; import NotFound from "./pages/NotFound";
import Sobre from "./pages/Sobre"; import Contato from "./pages/Contato"; import MapaDoSite from "./pages/MapaDoSite"; import TermosDeUso from "./pages/TermosDeUso"; import PoliticaPrivacidade from "./pages/PoliticaPrivacidade"; import MeuOrcamento from "./pages/MeuOrcamento";
import CalculadoraTinta from "./pages/CalculadoraTinta";
import CalculadoraDrywall from "./pages/CalculadoraDrywall"; import CalculadoraAzulejos from "./pages/CalculadoraAzulejos"; import CalculadoraRejunte from "./pages/CalculadoraRejunte"; import CalculadoraRodape from "./pages/CalculadoraRodape"; import CalculadoraDeck from "./pages/CalculadoraDeck"; import CalculadoraMuro from "./pages/CalculadoraMuro";
import CalculadoraPesoEstruturaTelhado from "./pages/CalculadoraPesoEstruturaTelhado"; import CalculadoraEscada from "./pages/CalculadoraEscada"; import CalculadoraRampa from "./pages/CalculadoraRampa"; import CalculadoraVidro from "./pages/CalculadoraVidro"; import CalculadoraPesoAluminio from "./pages/CalculadoraPesoAluminio";
import CalculadoraArCondicionado from "./pages/CalculadoraArCondicionado"; import CalculadoraIluminacao from "./pages/CalculadoraIluminacao"; import CalculadoraEnergia from "./pages/CalculadoraEnergia"; import CalculadoraFios from "./pages/CalculadoraFios"; import CalculadoraCaixaAgua from "./pages/CalculadoraCaixaAgua";
import ChecklistVistoria from "./pages/ChecklistVistoria"; import CalculadoraCronograma from "./pages/CalculadoraCronograma"; import CalculadoraMaoDeObra from "./pages/CalculadoraMaoDeObra"; import CalculadoraCFTV from "./pages/CalculadoraCFTV"; import CalculadoraMoveisPlanejados from "./pages/CalculadoraMoveisPlanejados"; import CalculadoraFinanciamento from "./pages/CalculadoraFinanciamento";
import CalculadoraCerca from "./pages/CalculadoraCerca"; import CalculadoraGrama from "./pages/CalculadoraGrama"; import CalculadoraPavers from "./pages/CalculadoraPavers"; import CalculadoraPiscina from "./pages/CalculadoraPiscina"; import CalculadoraChurrasco from "./pages/CalculadoraChurrasco"; import CalculadoraPapelParede from "./pages/CalculadoraPapelParede"; import CalculadoraCortinas from "./pages/CalculadoraCortinas";

const queryClient = new QueryClient();
const CalculadoraPisos = lazy(() => import("./pages/CalculadoraPisos"));
const CalculadoraTijolos = lazy(() => import("./pages/CalculadoraTijolos"));
const CalculadoraConcreto = lazy(() => import("./pages/CalculadoraConcreto"));
const CalculadoraTelhado = lazy(() => import("./pages/CalculadoraTelhado"));
const AppRoutes = () => <Routes>
  <Route path="/" element={<Index />} /><Route path="/meu-orcamento" element={<MeuOrcamento />} />
  <Route path="/calculadora-tinta" element={<CalculadoraTinta />} /><Route path="/calculadora-pisos" element={<CalculadoraPisos />} /><Route path="/calculadora-tijolos" element={<CalculadoraTijolos />} /><Route path="/calculadora-concreto" element={<CalculadoraConcreto />} /><Route path="/calculadora-telhado" element={<CalculadoraTelhado />} />
  <Route path="/calculadora-drywall" element={<CalculadoraDrywall />} /><Route path="/calculadora-azulejos" element={<CalculadoraAzulejos />} /><Route path="/calculadora-rejunte" element={<CalculadoraRejunte />} /><Route path="/calculadora-rodape" element={<CalculadoraRodape />} /><Route path="/calculadora-deck" element={<CalculadoraDeck />} /><Route path="/calculadora-muro" element={<CalculadoraMuro />} /><Route path="/calculadora-peso-estrutura-telhado" element={<CalculadoraPesoEstruturaTelhado />} /><Route path="/calculadora-escada" element={<CalculadoraEscada />} /><Route path="/calculadora-rampa" element={<CalculadoraRampa />} /><Route path="/calculadora-vidro" element={<CalculadoraVidro />} /><Route path="/calculadora-peso-aluminio" element={<CalculadoraPesoAluminio />} />
  <Route path="/calculadora-ar-condicionado" element={<CalculadoraArCondicionado />} /><Route path="/calculadora-iluminacao" element={<CalculadoraIluminacao />} /><Route path="/calculadora-energia" element={<CalculadoraEnergia />} /><Route path="/calculadora-fios" element={<CalculadoraFios />} /><Route path="/calculadora-caixa-agua" element={<CalculadoraCaixaAgua />} /><Route path="/checklist-vistoria" element={<ChecklistVistoria />} /><Route path="/calculadora-cronograma" element={<CalculadoraCronograma />} /><Route path="/calculadora-mao-de-obra" element={<CalculadoraMaoDeObra />} /><Route path="/calculadora-cftv" element={<CalculadoraCFTV />} /><Route path="/calculadora-moveis-planejados" element={<CalculadoraMoveisPlanejados />} /><Route path="/calculadora-financiamento" element={<CalculadoraFinanciamento />} />
  <Route path="/calculadora-cerca" element={<CalculadoraCerca />} /><Route path="/calculadora-grama" element={<CalculadoraGrama />} /><Route path="/calculadora-pavers" element={<CalculadoraPavers />} /><Route path="/calculadora-piscina" element={<CalculadoraPiscina />} /><Route path="/calculadora-churrasco" element={<CalculadoraChurrasco />} /><Route path="/calculadora-papel-parede" element={<CalculadoraPapelParede />} /><Route path="/calculadora-cortinas" element={<CalculadoraCortinas />} />
  <Route path="/termos-de-uso" element={<TermosDeUso />} /><Route path="/politica-de-privacidade" element={<PoliticaPrivacidade />} /><Route path="/contato" element={<Contato />} /><Route path="/sobre" element={<Sobre />} /><Route path="/mapa-do-site" element={<MapaDoSite />} /><Route path="/blog" element={<Blog />} /><Route path="/blog/erros-comuns-reformas-como-evitar" element={<Navigate to="/blog/erros-comuns-reformas-construcao" replace />} /><Route path="/blog/:slug" element={<BlogPost />} /><Route path="*" element={<NotFound />} />
</Routes>;
const App = ({ location, helmetContext }: { location?: string; helmetContext?: object } = {}) => <QueryClientProvider client={queryClient}><HelmetProvider context={helmetContext}><TooltipProvider><OrcamentoProvider><Toaster /><Sonner /><ConsentManager /><Suspense fallback={<div className="min-h-screen p-8 text-center">Carregando ferramenta…</div>}>{location ? <MemoryRouter initialEntries={[location]}><AppRoutes /></MemoryRouter> : <BrowserRouter><AppRoutes /></BrowserRouter>}</Suspense></OrcamentoProvider></TooltipProvider></HelmetProvider></QueryClientProvider>;
export default App;
