import { Toaster } from "@/components/ui/toaster";
import { lazy, Suspense } from "react";
import { Toaster as Sonner } from "@/components/ui/sonner";
import { TooltipProvider } from "@/components/ui/tooltip";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { BrowserRouter, MemoryRouter, Routes, Route, Navigate } from "react-router-dom";
import { HelmetProvider } from "react-helmet-async";
import { OrcamentoProvider } from "./context/OrcamentoProvider";
import ConsentManager from "./components/ConsentManager";
import ToolMethodology from "./components/ToolMethodology";
import { getToolQuality } from "./content/toolQuality";
import Index from "./pages/Index"; import Blog from "./pages/Blog"; import BlogPost from "./pages/BlogPost"; import NotFound from "./pages/NotFound";
import Sobre from "./pages/Sobre"; import Contato from "./pages/Contato"; import MapaDoSite from "./pages/MapaDoSite"; import TermosDeUso from "./pages/TermosDeUso"; import PoliticaPrivacidade from "./pages/PoliticaPrivacidade"; import MeuOrcamento from "./pages/MeuOrcamento";
import CalculadoraTinta from "./pages/CalculadoraTinta";
import CalculadoraPisos from "./pages/CalculadoraPisos"; import CalculadoraTijolos from "./pages/CalculadoraTijolos"; import CalculadoraConcreto from "./pages/CalculadoraConcreto"; import CalculadoraTelhado from "./pages/CalculadoraTelhado";
const CalculadoraDrywall = lazy(() => import("./pages/CalculadoraDrywall")); const CalculadoraAzulejos = lazy(() => import("./pages/CalculadoraAzulejos")); const CalculadoraRejunte = lazy(() => import("./pages/CalculadoraRejunte")); const CalculadoraRodape = lazy(() => import("./pages/CalculadoraRodape")); const CalculadoraDeck = lazy(() => import("./pages/CalculadoraDeck")); const CalculadoraMuro = lazy(() => import("./pages/CalculadoraMuro"));
const CalculadoraPesoEstruturaTelhado = lazy(() => import("./pages/CalculadoraPesoEstruturaTelhado")); const CalculadoraEscada = lazy(() => import("./pages/CalculadoraEscada")); const CalculadoraRampa = lazy(() => import("./pages/CalculadoraRampa")); const CalculadoraVidro = lazy(() => import("./pages/CalculadoraVidro")); const CalculadoraPesoAluminio = lazy(() => import("./pages/CalculadoraPesoAluminio"));
const CalculadoraArCondicionado = lazy(() => import("./pages/CalculadoraArCondicionado")); const CalculadoraIluminacao = lazy(() => import("./pages/CalculadoraIluminacao")); const CalculadoraEnergia = lazy(() => import("./pages/CalculadoraEnergia")); const CalculadoraFios = lazy(() => import("./pages/CalculadoraFios")); const CalculadoraCaixaAgua = lazy(() => import("./pages/CalculadoraCaixaAgua"));
const ChecklistVistoria = lazy(() => import("./pages/ChecklistVistoria")); const CalculadoraCronograma = lazy(() => import("./pages/CalculadoraCronograma")); const CalculadoraMaoDeObra = lazy(() => import("./pages/CalculadoraMaoDeObra")); const CalculadoraCFTV = lazy(() => import("./pages/CalculadoraCFTV")); const CalculadoraMoveisPlanejados = lazy(() => import("./pages/CalculadoraMoveisPlanejados")); const CalculadoraFinanciamento = lazy(() => import("./pages/CalculadoraFinanciamento"));
const CalculadoraCerca = lazy(() => import("./pages/CalculadoraCerca")); const CalculadoraGrama = lazy(() => import("./pages/CalculadoraGrama")); const CalculadoraPavers = lazy(() => import("./pages/CalculadoraPavers")); const CalculadoraPiscina = lazy(() => import("./pages/CalculadoraPiscina")); const CalculadoraChurrasco = lazy(() => import("./pages/CalculadoraChurrasco")); const CalculadoraPapelParede = lazy(() => import("./pages/CalculadoraPapelParede")); const CalculadoraCortinas = lazy(() => import("./pages/CalculadoraCortinas"));

const queryClient = new QueryClient();
const AppRoutes = () => <Routes>
  <Route path="/" element={<Index />} /><Route path="/meu-orcamento" element={<MeuOrcamento />} />
  <Route path="/calculadora-tinta" element={<CalculadoraTinta />} /><Route path="/calculadora-pisos" element={<><CalculadoraPisos /><ToolMethodology record={getToolQuality("/calculadora-pisos")!} /></>} /><Route path="/calculadora-tijolos" element={<><CalculadoraTijolos /><ToolMethodology record={getToolQuality("/calculadora-tijolos")!} /></>} /><Route path="/calculadora-concreto" element={<><CalculadoraConcreto /><ToolMethodology record={getToolQuality("/calculadora-concreto")!} /></>} /><Route path="/calculadora-telhado" element={<><CalculadoraTelhado /><ToolMethodology record={getToolQuality("/calculadora-telhado")!} /></>} />
  <Route path="/calculadora-drywall" element={<CalculadoraDrywall />} /><Route path="/calculadora-azulejos" element={<CalculadoraAzulejos />} /><Route path="/calculadora-rejunte" element={<CalculadoraRejunte />} /><Route path="/calculadora-rodape" element={<CalculadoraRodape />} /><Route path="/calculadora-deck" element={<CalculadoraDeck />} /><Route path="/calculadora-muro" element={<CalculadoraMuro />} /><Route path="/calculadora-peso-estrutura-telhado" element={<CalculadoraPesoEstruturaTelhado />} /><Route path="/calculadora-escada" element={<CalculadoraEscada />} /><Route path="/calculadora-rampa" element={<CalculadoraRampa />} /><Route path="/calculadora-vidro" element={<CalculadoraVidro />} /><Route path="/calculadora-peso-aluminio" element={<CalculadoraPesoAluminio />} />
  <Route path="/calculadora-ar-condicionado" element={<CalculadoraArCondicionado />} /><Route path="/calculadora-iluminacao" element={<CalculadoraIluminacao />} /><Route path="/calculadora-energia" element={<CalculadoraEnergia />} /><Route path="/calculadora-fios" element={<CalculadoraFios />} /><Route path="/calculadora-caixa-agua" element={<CalculadoraCaixaAgua />} /><Route path="/checklist-vistoria" element={<ChecklistVistoria />} /><Route path="/calculadora-cronograma" element={<CalculadoraCronograma />} /><Route path="/calculadora-mao-de-obra" element={<CalculadoraMaoDeObra />} /><Route path="/calculadora-cftv" element={<CalculadoraCFTV />} /><Route path="/calculadora-moveis-planejados" element={<CalculadoraMoveisPlanejados />} /><Route path="/calculadora-financiamento" element={<CalculadoraFinanciamento />} />
  <Route path="/calculadora-cerca" element={<CalculadoraCerca />} /><Route path="/calculadora-grama" element={<CalculadoraGrama />} /><Route path="/calculadora-pavers" element={<CalculadoraPavers />} /><Route path="/calculadora-piscina" element={<CalculadoraPiscina />} /><Route path="/calculadora-churrasco" element={<CalculadoraChurrasco />} /><Route path="/calculadora-papel-parede" element={<CalculadoraPapelParede />} /><Route path="/calculadora-cortinas" element={<CalculadoraCortinas />} />
  <Route path="/termos-de-uso" element={<TermosDeUso />} /><Route path="/politica-de-privacidade" element={<PoliticaPrivacidade />} /><Route path="/contato" element={<Contato />} /><Route path="/sobre" element={<Sobre />} /><Route path="/mapa-do-site" element={<MapaDoSite />} /><Route path="/blog" element={<Blog />} /><Route path="/blog/erros-comuns-reformas-como-evitar" element={<Navigate to="/blog/erros-comuns-reformas-construcao" replace />} /><Route path="/blog/:slug" element={<BlogPost />} /><Route path="*" element={<NotFound />} />
</Routes>;
const App = ({ location, helmetContext }: { location?: string; helmetContext?: object } = {}) => <QueryClientProvider client={queryClient}><HelmetProvider context={helmetContext}><TooltipProvider><OrcamentoProvider><Toaster /><Sonner /><ConsentManager /><Suspense fallback={<div className="min-h-screen p-8 text-center">Carregando ferramenta…</div>}>{location ? <MemoryRouter initialEntries={[location]}><AppRoutes /></MemoryRouter> : <BrowserRouter><AppRoutes /></BrowserRouter>}</Suspense></OrcamentoProvider></TooltipProvider></HelmetProvider></QueryClientProvider>;
export default App;
